FROM node:21 AS build

RUN mkdir -p /usr/src/my-store

WORKDIR /usr/src/my-store

ARG NODE_ENV
ARG DB_USER
ARG DB_PASSWORD
ARG DB_HOST
ARG DB_NAME
ARG DATABASE_URL
ARG API_KEY
ARG JWT_SECRET
ARG SMTP_EMAIL
ARG SMTP_PASSWORD


ENV NODE_ENV=$NODE_ENV
ENV DB_USER=$DB_USER
ENV DB_PASSWORD=$DB_PASSWORD
ENV DB_HOST=$DB_HOST
ENV DB_NAME=$DB_NAME
ENV DATABASE_URL=$DATABASE_URL
ENV API_KEY=$API_KEY
ENV JWT_SECRET=$JWT_SECRET
ENV SMTP_EMAIL=$SMTP_EMAIL
ENV SMTP_PASSWORD=$SMTP_PASSWORD

COPY package*.json ./
RUN npm ci

COPY . .


EXPOSE 8080

CMD ["npm", "start"]
